nodeLinker: 'node-modules'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'

yarnPath: .yarn/releases/yarn-3.2.3.cjs

packageExtensions:
  '@parcel/workers@*':
    peerDependenciesMeta:
      '@parcel/core':
        optional: true
  '@parcel/fs@*':
    peerDependenciesMeta:
      '@parcel/core':
        optional: true
  '@parcel/cache@*':
    peerDependenciesMeta:
      '@parcel/core':
        optional: true
  '@parcel/package-manager@*':
    peerDependenciesMeta:
      '@parcel/core':
        optional: true
