export enum Material {
	Adamantine = 'adamantine',
	Bone = 'bone',
	Bronze = 'brone',
	Cloth = 'cloth',
	ColdIron = 'cold iron',
	Hide = 'hide',
	Iron = 'iron',
	Leather = 'leather',
	Mithral = 'mithral',
	Silver = 'silver',
	Steel = 'steel',
	Stone = 'stone',
	Wood = 'wood',
}
