name: Check & Merge

on:
  push:
    branches: ['develop']
  workflow_dispatch:

jobs:
  check:
    name: Static Checks
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Static Checks
        run: yarn check:all

  main:
    name: Create PR Develop to Main
    concurrency: ci-${{ github.ref }}
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v3

      # https://github.com/marketplace/actions/github-pull-request-action
      - name: create pull request
        id: open-pr
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: ${{ github.event.repository.default_branch }}
          pr_title: '[Automated] Merge ${{ github.ref_name }} into ${{ github.event.repository.default_branch }}'
          pr_label: 'pipeline'
          pr_body: 'Automated Pull Request'

      # https://github.com/marketplace/actions/merge-pull-requests-automerge-action
      - name: merge pull request
        uses: 'pascalgn/automerge-action@v0.15.5'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          PULL_REQUEST: ${{ steps.open-pr.outputs.pr_number }}
          MERGE_LABELS: 'pipeline'
          UPDATE_LABELS: 'pipeline'
          MERGE_ERROR_FAIL: true
          MERGE_FILTER_AUTHOR: 'github-actions'
          MERGE_REQUIRED_APPROVALS: 0
