name: Check & Merge

on:
  push:
    branches:
      - 'develop'

env:
  BRANCH_NAME: staging

jobs:
  setup:
    name: Setup
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.push.head.ref }}

      - name: Setup git
        run: |
          git config --global user.email "${GITHUB_ACTOR}"
          git config --global user.name "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: remove old staging
        continue-on-error: true
        run: |
          git remote update
          git fetch
          git push -d origin ${{ env.BRANCH_NAME }}

      - name: Setup staging branch
        run: |
          git checkout -b ${{ env.BRANCH_NAME }}
          git merge origin/${{ github.event.repository.default_branch }}
          git push --set-upstream origin ${{ env.BRANCH_NAME }}

  check:
    name: Static Checks
    concurrency: ci-${{ github.ref }}
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH_NAME }}

      - name: Setpup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Static Checks
        run: yarn check:all

  main:
    name: Merge to main
    concurrency: ci-${{ github.ref }}
    needs: check
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ env.BRANCH_NAME }}
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH_NAME }}

      # https://github.com/marketplace/actions/github-pull-request-action
      - name: create pull request
        id: open-pr
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: ${{ github.event.repository.default_branch }}
          pr_title: '[Automated] Merge ${{ github.ref_name }} into ${{ github.event.repository.default_branch }}'
          pr_label: 'pipeline'
          pr_body: 'Automated Pull Request'

      # https://github.com/juliangruber/merge-pull-request-action
      - name: Merge Pull Request
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.open-pr.outputs.pr_number }}
          method: merge

      - name: Cleanup
        run: |
          git config --global user.email "${GITHUB_ACTOR}"
          git config --global user.name "${GITHUB_ACTOR}@users.noreply.github.com"
          git remote update
          git fetch
          git push -d origin ${{ env.BRANCH_NAME }}
